# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ed81f95e12c3703619a2832fc0d9ad1fe7f10c53fcab617e3d868b935a77e115d9d3fd2986e85d20a9910d21f30e4b80f1a125bafcccc45e89d127bb65dd1b

test:
  secret_key_base: b49ee385615a1db0ddbdd9e46d7799ba77ee34afd30acd2f08fc10aeb256c7fa0dcb7f34be413195a03227e92cb5f20b60e088ff00f017b586080880f4d9192a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
